# Generated by Django 5.0.6 on 2024-06-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.TextField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('MECH', 'MECH'), ('EEE', 'EE')], null=True),
        ),
    ]
